### ISSUE TITLE
Add macOS wheel + tar.gz (sdist) to PyPI

### ISSUE THREAD

**Issue by aviramha** [thedrow/fastuuid#1]
Easiest way would be to add CI for that. Would it be OK if I send a PR using azure pipelines? (`orjson` has good examples)

**Comment by thedrow** [comment]
I'm currently using Travis-CI.
I don't really need to switch though unless you have a good reason for me to do so.

**Comment by aviramha** [comment]
This is probably doable on Travis also, but I suggested using Azure as there's boilerplate for that

**Comment by thedrow** [comment]
I've enabled Azure Pipelines.

**Comment by aviramha** [comment]
> I've enabled Azure Pipelines.

I'll do the macOS wheels after my other PR is merged to avoid double work.
I'll probably just do it on Travis instead of Azure - I thought debugging CI is problematic if I'm not the repo owner, which appears to be wrong.

**Comment by thedrow** [comment]
sdists are released.

**Comment by messense** [comment]
Please consider moving to GitHub Actions. We now have [maturin-action](https://github.com/messense/maturin-action) supports building wheels for windows(x86_64/i686), macOS (x86_64/aarch64/univeral2) and linux(x86_64/i686/aarch64/armv7l/ppc64le/s390x).

Example: https://github.com/messense/crfs-rs/blob/0efac4ca50e96d7f1098b49f565c6a9010c55389/.github/workflows/Python.yml
