### ISSUE TITLE
Wheels for python 3.11

### ISSUE THREAD

**Issue by kasium** [thedrow/fastuuid#20]
Hello,
can you please release wheels for python 3.11 since the release is in a few days?

Thanks a lot!

**Comment by kasium** [comment]
Had somebody time to look into this?

**Comment by thedrow** [comment]
We should probably migrate from [travis](https://github.com/thedrow/fastuuid/blob/master/.travis.yml) to github actions.
It'd be easier to release wheels then.

**Comment by kasium** [comment]
@thedrow I can see that py3.11 support was added by https://github.com/thedrow/fastuuid/commit/31fd88bb557469431756d04768981d29e8f30ee5. However, the last release doesn't contain no python3.11 wheel. Can you please create a new release containing the missing wheels?

**Comment by kasium** [comment]
And of course now the wheels for python 3.12 are missing as well
