### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by kasium** [thedrow/fastuuid#21]
Hey,
would it be possible to add type hints to the package? They could mostly be copied from the stdlib (tyoeshed/stdlib). As an alternative thy could be added to typeshed/stubs.

What do you think?

**Comment by thedrow** [comment]
I don't know how to add type hints through PyO3 but we should find out.

**Comment by kasium** [comment]
Else it's possible to add stubs to typeshed. Just wanted to check here first

**Comment by enerqi** [comment]
[Docs are in the pyo3 appendix](https://pyo3.rs/v0.17.2/python_typing_hints.html)

**Comment by thedrow** [comment]
Feel free to contribute those

**Comment by kasium** [comment]
@thedrow would you please consider to do a release? 😄

**Comment by thedrow** [comment]
When I'll have time, sure :)
