### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by kasium** [thedrow/fastuuid#28]
It would be great if the library could add and expose type hints, so that mypy dosen't not complain if fastuuid is used

**Comment by thedrow** [comment]
Contributions are welcome.

**Comment by kasium** [comment]
Great, let me check if I can contribute.

BTW, is this project still active since there is no recent release and no wheels for py 3.11/12

**Comment by thedrow** [comment]
I have added a collaborator and we'll try to keep this repo up to date.

**Comment by kasium** [comment]
Thanks, since type hints are added, we can close this
